data:
  corpus:                                 # Pass to dataloader
    # The following depends on corpus
    name: 'DLHLP'                         # Specify corpus
    path: '/work/b07u1234/b06502162/HW1/model1/DLHLP'
    dev_split: ['dev']
    test_split: ['test']
    bucketing: False
    batch_size: 1
src:
  config: '/work/b07u1234/b06502162/HW1/model1/End-to-end-ASR/config/dlhlp_asr.yaml'
  ckpt: '/work/b07u1234/b06502162/HW1/model1/ckpt/naive/best_ctc_dev.pth'

decode:
  beam_size: 1
  min_len_ratio: 0.01
  max_len_ratio: 0.30
  lm_path: '/data/storage/harry/test_env/dlhlp_ckpt/hw1_best_ppx.pth'
  lm_config: 'config/dlhlp_lm.yaml'
  lm_weight: 0.7
  ctc_weight: 0
